name: linting, testing, build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint
        if: always()
      - name: linting css
        run: npm run stylelint
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: storybook build
        run: npm run storybook:build
        if: always()
      - name: update screenshot
        run: npx loki update --storiesFilter="^shared\\/AppLink Default App Link|shared\\/AppLink Outlined App Link|widget\\/Navbar Dark Navbar|widget\\/Sidebar Light Sidebar|widget\\/Sidebar Dark Sidebar\$" --reactUri="file:./storybook-static"
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always(
